US_KEYBOARD_LAYOUT = [
    {
        '`': {'normal': '`', 'shift': '~', 'length': 1},
        '1': {'normal': '1', 'shift': '!', 'length': 1},
        '2': {'normal': '2', 'shift': '@', 'length': 1},
        '3': {'normal': '3', 'shift': '#', 'length': 1},
        '4': {'normal': '4', 'shift': '$', 'length': 1},
        '5': {'normal': '5', 'shift': '%', 'length': 1},
        '6': {'normal': '6', 'shift': '^', 'length': 1},
        '7': {'normal': '7', 'shift': '&', 'length': 1},
        '8': {'normal': '8', 'shift': '*', 'length': 1},
        '9': {'normal': '9', 'shift': '(', 'length': 1},
        '0': {'normal': '0', 'shift': ')', 'length': 1},
        '-': {'normal': '-', 'shift': '_', 'length': 1},
        '=': {'normal': '=', 'shift': '+', 'length': 1},
        'BKSP': {'normal': 'BKSP', 'shift': 'BKSP', 'length': 2},
    },
    {
        'TAB': {'normal': 'TAB', 'shift': 'TAB', 'length': 1.5},
        'q': {'normal': 'q', 'shift': 'Q', 'length': 1},
        'w': {'normal': 'w', 'shift': 'W', 'length': 1},
        'e': {'normal': 'e', 'shift': 'E', 'length': 1},
        'r': {'normal': 'r', 'shift': 'R', 'length': 1},
        't': {'normal': 't', 'shift': 'T', 'length': 1},
        'y': {'normal': 'y', 'shift': 'Y', 'length': 1},
        'u': {'normal': 'u', 'shift': 'U', 'length': 1},
        'i': {'normal': 'i', 'shift': 'I', 'length': 1},
        'o': {'normal': 'o', 'shift': 'O', 'length': 1},
        'p': {'normal': 'p', 'shift': 'P', 'length': 1},
        '[': {'normal': '[', 'shift': '{', 'length': 1},
        ']': {'normal': ']', 'shift': '}', 'length': 1},
        '\\': {'normal': '\\', 'shift': '|', 'length': 1.5},
    },
    {
        'CAPS': {'normal': 'CAPS', 'shift': 'CAPS', 'length': 1.8},
        'a': {'normal': 'a', 'shift': 'A', 'length': 1},
        's': {'normal': 's', 'shift': 'S', 'length': 1},
        'd': {'normal': 'd', 'shift': 'D', 'length': 1},
        'f': {'normal': 'f', 'shift': 'F', 'length': 1},
        'g': {'normal': 'g', 'shift': 'G', 'length': 1},
        'h': {'normal': 'h', 'shift': 'H', 'length': 1},
        'j': {'normal': 'j', 'shift': 'J', 'length': 1},
        'k': {'normal': 'k', 'shift': 'K', 'length': 1},
        'l': {'normal': 'l', 'shift': 'L', 'length': 1},
        ';': {'normal': ';', 'shift': ':', 'length': 1},
        "'": {'normal': "'", 'shift': '"', 'length': 1},
        'ENTER': {'normal': 'ENTER', 'shift': 'ENTER', 'length': 2.4},
    },
    {
        'SHIFT': {'normal': 'SHIFT', 'shift': 'SHIFT', 'length': 2.8},
        'z': {'normal': 'z', 'shift': 'Z', 'length': 1},
        'x': {'normal': 'x', 'shift': 'X', 'length': 1},
        'c': {'normal': 'c', 'shift': 'C', 'length': 1},
        'v': {'normal': 'v', 'shift': 'V', 'length': 1},
        'b': {'normal': 'b', 'shift': 'B', 'length': 1},
        'n': {'normal': 'n', 'shift': 'N', 'length': 1},
        'm': {'normal': 'm', 'shift': 'M', 'length': 1},
        ',': {'normal': ',', 'shift': '<', 'length': 1},
        '.': {'normal': '.', 'shift': '>', 'length': 1},
        '/': {'normal': '/', 'shift': '?', 'length': 1},
        'SHIFT_2': {'normal': 'SHIFT', 'shift': 'SHIFT', 'length': 2.8},
    },
    {
        'CTRL': {'normal': 'CTRL', 'shift': 'CTRL', 'length': 1.4},
        'WIN': {'normal': 'WIN', 'shift': 'WIN', 'length': 1.4},
        'ALT': {'normal': 'ALT', 'shift': 'ALT', 'length': 1.4},
        'SPACE': {'normal': 'SPACE', 'shift': 'SPACE', 'length': 8.3},
        'ALT_2': {'normal': 'ALT', 'shift': 'ALT', 'length': 1.4},
        'FN': {'normal': 'FN', 'shift': 'FN', 'length': 1.4},
        'CTRL_2': {'normal': 'CTRL', 'shift': 'CTRL', 'length': 1.4},
    }
]

temp = [
    ['`~', '1!', '2@', '3#', '4$', '5%', '6^', '7&', '8*', '9(', '0)', '-_', '=+', 'BKSP'],
    ['TAB', 'qQ', 'wW', 'eE', 'rR', 'tT', 'yY', 'uU', 'iI', 'oO', 'pP', '[{', ']}', '\\|'],
    ['CAPS', 'aA', 'sS', 'dD', 'fF', 'gG', 'hH', 'jJ', 'kK', 'lL', ';:', '\'"', 'ENTER'],
    ['SHIFT', 'zZ', 'xX', 'cC', 'vV', 'bB', 'nN', 'mM', ',<', '.>', '/?', 'SHIFT'],
    ['CTRL', 'WIN', 'ALT', 'SPACE', 'ALT', 'FN', 'CTRL']
]
